apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: java-app-rs
  labels:
    app: java-app-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-sample-app
  template:
    metadata:
      labels:
        app: java-sample-app
    spec:
      containers:
        - name: java-app
          image: bvinodkumar2008/java-docker:latest
          ports:
            - name: java-app-port
              containerPort: 8080
